theme: jekyll-theme-cayman
title: Aukhatov's Blog
name: Arthur Aukhatov Blog
email: aaukhatov@gmail.com
description: Here you can find something helpful for yourself
footer-links:
  github: aukhatov
  twitter: aaukhatov
