theme: jekyll-theme-cayman
title: Aukhatov's Blog
description: Here you can find something helpful for yourself
author:
  name: Arthur Aukhatov
  email: aaukhatov@gmail.com
  
copyright: © 2019
baseurl: ""
footer-links:
  github: aukhatov
  twitter: aaukhatov
header_pages:
 - about.md

google_analytics: UA-136638592-1

excerpt_separator: "<!--excerpt-->"
plugins:
  - jekyll-sitemap
